name: json_dynamic_widget_annotation
description: Annotation for json_dynamic_widget_generator
version: 0.1.0
repository: https://github.com/massa-org/json_dynamic_widget_generator

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.4.0
  json_dynamic_widget: ^5.0.0
  theme_json_converter: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
