name: json_dynamic_widget_generator
description: Generate builder for widget to use it with json_dynamic_widget
version: 0.0.2
homepage: https://github.com/massa-org/json_dynamic_widget_generator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

  
dependencies:
  flutter:
    sdk: flutter
  recase: ^4.0.0
  json_dynamic_widget_annotation: ^0.0.1

  theme_json_converter: ^0.0.1
    
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  pedantic: ^1.11.1
  flutter_lints: ^1.0.0


  
