name: json_dynamic_widget_generator
description: Generate builder for widget to use it with json_dynamic_widget
version: 0.1.0
repository: https://github.com/massa-org/json_dynamic_widget_generator

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

  
dependencies:
  flutter:
    sdk: flutter
  recase: ^4.0.0

  json_dynamic_widget_annotation: ^0.1.0
  theme_json_converter: ^0.1.0
    
  build: ^2.0.0
  source_gen: ^1.1.0
  analyzer: '>=2.0.0 <6.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  flutter_lints: ^2.0.0


  
